/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerificarRouteImport } from './routes/verificar'
import { Route as TimesRouteImport } from './routes/times'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResultadosRouteImport } from './routes/resultados'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LocaisRouteImport } from './routes/locais'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AtletasRouteImport } from './routes/atletas'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TimesSlugRouteImport } from './routes/times.$slug'
import { Route as SumulaPartidaIdRouteImport } from './routes/sumula.$partidaId'
import { Route as PartidasIdRouteImport } from './routes/partidas.$id'
import { Route as OnboardingTorcedorRouteImport } from './routes/onboarding.torcedor'
import { Route as OnboardingJogadorRouteImport } from './routes/onboarding.jogador'
import { Route as OnboardingDiretorRouteImport } from './routes/onboarding.diretor'
import { Route as ManifestoSlugRouteImport } from './routes/manifesto.$slug'
import { Route as ConviteCodeRouteImport } from './routes/convite.$code'
import { Route as AtletasIdRouteImport } from './routes/atletas.$id'
import { Route as AuthenticatedMinhaContaRouteImport } from './routes/_authenticated/minha-conta'
import { Route as AuthenticatedInscricaoRouteImport } from './routes/_authenticated/inscricao'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedMinhaContaExcluirContaRouteImport } from './routes/_authenticated/minha-conta/excluir-conta'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin/usuarios'
import { Route as AuthenticatedAdminTriagemRouteImport } from './routes/_authenticated/admin/triagem'
import { Route as AuthenticatedAdminTimesRouteImport } from './routes/_authenticated/admin/times'
import { Route as AuthenticatedAdminSumulasRouteImport } from './routes/_authenticated/admin/sumulas'
import { Route as AuthenticatedAdminSorteioRouteImport } from './routes/_authenticated/admin/sorteio'
import { Route as AuthenticatedAdminNotificacoesRouteImport } from './routes/_authenticated/admin/notificacoes'
import { Route as AuthenticatedAdminMasterSwitchRouteImport } from './routes/_authenticated/admin/master-switch'
import { Route as AuthenticatedAdminLigasRouteImport } from './routes/_authenticated/admin/ligas'
import { Route as AuthenticatedAdminFinanceiroRouteImport } from './routes/_authenticated/admin/financeiro'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as ApiPublicHooksWoCheckerRouteImport } from './routes/api/public/hooks/wo-checker'

const VerificarRoute = VerificarRouteImport.update({
  id: '/verificar',
  path: '/verificar',
  getParentRoute: () => rootRouteImport,
} as any)
const TimesRoute = TimesRouteImport.update({
  id: '/times',
  path: '/times',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultadosRoute = ResultadosRouteImport.update({
  id: '/resultados',
  path: '/resultados',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaisRoute = LocaisRouteImport.update({
  id: '/locais',
  path: '/locais',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AtletasRoute = AtletasRouteImport.update({
  id: '/atletas',
  path: '/atletas',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TimesSlugRoute = TimesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TimesRoute,
} as any)
const SumulaPartidaIdRoute = SumulaPartidaIdRouteImport.update({
  id: '/sumula/$partidaId',
  path: '/sumula/$partidaId',
  getParentRoute: () => rootRouteImport,
} as any)
const PartidasIdRoute = PartidasIdRouteImport.update({
  id: '/partidas/$id',
  path: '/partidas/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingTorcedorRoute = OnboardingTorcedorRouteImport.update({
  id: '/torcedor',
  path: '/torcedor',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingJogadorRoute = OnboardingJogadorRouteImport.update({
  id: '/jogador',
  path: '/jogador',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingDiretorRoute = OnboardingDiretorRouteImport.update({
  id: '/diretor',
  path: '/diretor',
  getParentRoute: () => OnboardingRoute,
} as any)
const ManifestoSlugRoute = ManifestoSlugRouteImport.update({
  id: '/manifesto/$slug',
  path: '/manifesto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteCodeRoute = ConviteCodeRouteImport.update({
  id: '/convite/$code',
  path: '/convite/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AtletasIdRoute = AtletasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AtletasRoute,
} as any)
const AuthenticatedMinhaContaRoute = AuthenticatedMinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInscricaoRoute = AuthenticatedInscricaoRouteImport.update({
  id: '/inscricao',
  path: '/inscricao',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMinhaContaExcluirContaRoute =
  AuthenticatedMinhaContaExcluirContaRouteImport.update({
    id: '/excluir-conta',
    path: '/excluir-conta',
    getParentRoute: () => AuthenticatedMinhaContaRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTriagemRoute =
  AuthenticatedAdminTriagemRouteImport.update({
    id: '/triagem',
    path: '/triagem',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTimesRoute = AuthenticatedAdminTimesRouteImport.update({
  id: '/times',
  path: '/times',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSumulasRoute =
  AuthenticatedAdminSumulasRouteImport.update({
    id: '/sumulas',
    path: '/sumulas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSorteioRoute =
  AuthenticatedAdminSorteioRouteImport.update({
    id: '/sorteio',
    path: '/sorteio',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNotificacoesRoute =
  AuthenticatedAdminNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMasterSwitchRoute =
  AuthenticatedAdminMasterSwitchRouteImport.update({
    id: '/master-switch',
    path: '/master-switch',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLigasRoute = AuthenticatedAdminLigasRouteImport.update({
  id: '/ligas',
  path: '/ligas',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminFinanceiroRoute =
  AuthenticatedAdminFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicHooksWoCheckerRoute = ApiPublicHooksWoCheckerRouteImport.update({
  id: '/api/public/hooks/wo-checker',
  path: '/api/public/hooks/wo-checker',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/atletas': typeof AtletasRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/locais': typeof LocaisRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/ranking': typeof RankingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resultados': typeof ResultadosRoute
  '/signup': typeof SignupRoute
  '/termos': typeof TermosRoute
  '/times': typeof TimesRouteWithChildren
  '/verificar': typeof VerificarRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/inscricao': typeof AuthenticatedInscricaoRoute
  '/minha-conta': typeof AuthenticatedMinhaContaRouteWithChildren
  '/atletas/$id': typeof AtletasIdRoute
  '/convite/$code': typeof ConviteCodeRoute
  '/manifesto/$slug': typeof ManifestoSlugRoute
  '/onboarding/diretor': typeof OnboardingDiretorRoute
  '/onboarding/jogador': typeof OnboardingJogadorRoute
  '/onboarding/torcedor': typeof OnboardingTorcedorRoute
  '/partidas/$id': typeof PartidasIdRoute
  '/sumula/$partidaId': typeof SumulaPartidaIdRoute
  '/times/$slug': typeof TimesSlugRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/admin/ligas': typeof AuthenticatedAdminLigasRoute
  '/admin/master-switch': typeof AuthenticatedAdminMasterSwitchRoute
  '/admin/notificacoes': typeof AuthenticatedAdminNotificacoesRoute
  '/admin/sorteio': typeof AuthenticatedAdminSorteioRoute
  '/admin/sumulas': typeof AuthenticatedAdminSumulasRoute
  '/admin/times': typeof AuthenticatedAdminTimesRoute
  '/admin/triagem': typeof AuthenticatedAdminTriagemRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/minha-conta/excluir-conta': typeof AuthenticatedMinhaContaExcluirContaRoute
  '/api/public/hooks/wo-checker': typeof ApiPublicHooksWoCheckerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/atletas': typeof AtletasRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/locais': typeof LocaisRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/ranking': typeof RankingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resultados': typeof ResultadosRoute
  '/signup': typeof SignupRoute
  '/termos': typeof TermosRoute
  '/times': typeof TimesRouteWithChildren
  '/verificar': typeof VerificarRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/inscricao': typeof AuthenticatedInscricaoRoute
  '/minha-conta': typeof AuthenticatedMinhaContaRouteWithChildren
  '/atletas/$id': typeof AtletasIdRoute
  '/convite/$code': typeof ConviteCodeRoute
  '/manifesto/$slug': typeof ManifestoSlugRoute
  '/onboarding/diretor': typeof OnboardingDiretorRoute
  '/onboarding/jogador': typeof OnboardingJogadorRoute
  '/onboarding/torcedor': typeof OnboardingTorcedorRoute
  '/partidas/$id': typeof PartidasIdRoute
  '/sumula/$partidaId': typeof SumulaPartidaIdRoute
  '/times/$slug': typeof TimesSlugRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/admin/ligas': typeof AuthenticatedAdminLigasRoute
  '/admin/master-switch': typeof AuthenticatedAdminMasterSwitchRoute
  '/admin/notificacoes': typeof AuthenticatedAdminNotificacoesRoute
  '/admin/sorteio': typeof AuthenticatedAdminSorteioRoute
  '/admin/sumulas': typeof AuthenticatedAdminSumulasRoute
  '/admin/times': typeof AuthenticatedAdminTimesRoute
  '/admin/triagem': typeof AuthenticatedAdminTriagemRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/minha-conta/excluir-conta': typeof AuthenticatedMinhaContaExcluirContaRoute
  '/api/public/hooks/wo-checker': typeof ApiPublicHooksWoCheckerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/agenda': typeof AgendaRoute
  '/atletas': typeof AtletasRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/locais': typeof LocaisRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/ranking': typeof RankingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resultados': typeof ResultadosRoute
  '/signup': typeof SignupRoute
  '/termos': typeof TermosRoute
  '/times': typeof TimesRouteWithChildren
  '/verificar': typeof VerificarRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/inscricao': typeof AuthenticatedInscricaoRoute
  '/_authenticated/minha-conta': typeof AuthenticatedMinhaContaRouteWithChildren
  '/atletas/$id': typeof AtletasIdRoute
  '/convite/$code': typeof ConviteCodeRoute
  '/manifesto/$slug': typeof ManifestoSlugRoute
  '/onboarding/diretor': typeof OnboardingDiretorRoute
  '/onboarding/jogador': typeof OnboardingJogadorRoute
  '/onboarding/torcedor': typeof OnboardingTorcedorRoute
  '/partidas/$id': typeof PartidasIdRoute
  '/sumula/$partidaId': typeof SumulaPartidaIdRoute
  '/times/$slug': typeof TimesSlugRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/_authenticated/admin/ligas': typeof AuthenticatedAdminLigasRoute
  '/_authenticated/admin/master-switch': typeof AuthenticatedAdminMasterSwitchRoute
  '/_authenticated/admin/notificacoes': typeof AuthenticatedAdminNotificacoesRoute
  '/_authenticated/admin/sorteio': typeof AuthenticatedAdminSorteioRoute
  '/_authenticated/admin/sumulas': typeof AuthenticatedAdminSumulasRoute
  '/_authenticated/admin/times': typeof AuthenticatedAdminTimesRoute
  '/_authenticated/admin/triagem': typeof AuthenticatedAdminTriagemRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/minha-conta/excluir-conta': typeof AuthenticatedMinhaContaExcluirContaRoute
  '/api/public/hooks/wo-checker': typeof ApiPublicHooksWoCheckerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/atletas'
    | '/forgot-password'
    | '/locais'
    | '/login'
    | '/onboarding'
    | '/privacidade'
    | '/ranking'
    | '/reset-password'
    | '/resultados'
    | '/signup'
    | '/termos'
    | '/times'
    | '/verificar'
    | '/admin'
    | '/inscricao'
    | '/minha-conta'
    | '/atletas/$id'
    | '/convite/$code'
    | '/manifesto/$slug'
    | '/onboarding/diretor'
    | '/onboarding/jogador'
    | '/onboarding/torcedor'
    | '/partidas/$id'
    | '/sumula/$partidaId'
    | '/times/$slug'
    | '/admin/dashboard'
    | '/admin/financeiro'
    | '/admin/ligas'
    | '/admin/master-switch'
    | '/admin/notificacoes'
    | '/admin/sorteio'
    | '/admin/sumulas'
    | '/admin/times'
    | '/admin/triagem'
    | '/admin/usuarios'
    | '/minha-conta/excluir-conta'
    | '/api/public/hooks/wo-checker'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/atletas'
    | '/forgot-password'
    | '/locais'
    | '/login'
    | '/onboarding'
    | '/privacidade'
    | '/ranking'
    | '/reset-password'
    | '/resultados'
    | '/signup'
    | '/termos'
    | '/times'
    | '/verificar'
    | '/admin'
    | '/inscricao'
    | '/minha-conta'
    | '/atletas/$id'
    | '/convite/$code'
    | '/manifesto/$slug'
    | '/onboarding/diretor'
    | '/onboarding/jogador'
    | '/onboarding/torcedor'
    | '/partidas/$id'
    | '/sumula/$partidaId'
    | '/times/$slug'
    | '/admin/dashboard'
    | '/admin/financeiro'
    | '/admin/ligas'
    | '/admin/master-switch'
    | '/admin/notificacoes'
    | '/admin/sorteio'
    | '/admin/sumulas'
    | '/admin/times'
    | '/admin/triagem'
    | '/admin/usuarios'
    | '/minha-conta/excluir-conta'
    | '/api/public/hooks/wo-checker'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/agenda'
    | '/atletas'
    | '/forgot-password'
    | '/locais'
    | '/login'
    | '/onboarding'
    | '/privacidade'
    | '/ranking'
    | '/reset-password'
    | '/resultados'
    | '/signup'
    | '/termos'
    | '/times'
    | '/verificar'
    | '/_authenticated/admin'
    | '/_authenticated/inscricao'
    | '/_authenticated/minha-conta'
    | '/atletas/$id'
    | '/convite/$code'
    | '/manifesto/$slug'
    | '/onboarding/diretor'
    | '/onboarding/jogador'
    | '/onboarding/torcedor'
    | '/partidas/$id'
    | '/sumula/$partidaId'
    | '/times/$slug'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/financeiro'
    | '/_authenticated/admin/ligas'
    | '/_authenticated/admin/master-switch'
    | '/_authenticated/admin/notificacoes'
    | '/_authenticated/admin/sorteio'
    | '/_authenticated/admin/sumulas'
    | '/_authenticated/admin/times'
    | '/_authenticated/admin/triagem'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/minha-conta/excluir-conta'
    | '/api/public/hooks/wo-checker'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AgendaRoute: typeof AgendaRoute
  AtletasRoute: typeof AtletasRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LocaisRoute: typeof LocaisRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  PrivacidadeRoute: typeof PrivacidadeRoute
  RankingRoute: typeof RankingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResultadosRoute: typeof ResultadosRoute
  SignupRoute: typeof SignupRoute
  TermosRoute: typeof TermosRoute
  TimesRoute: typeof TimesRouteWithChildren
  VerificarRoute: typeof VerificarRoute
  ConviteCodeRoute: typeof ConviteCodeRoute
  ManifestoSlugRoute: typeof ManifestoSlugRoute
  PartidasIdRoute: typeof PartidasIdRoute
  SumulaPartidaIdRoute: typeof SumulaPartidaIdRoute
  ApiPublicHooksWoCheckerRoute: typeof ApiPublicHooksWoCheckerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verificar': {
      id: '/verificar'
      path: '/verificar'
      fullPath: '/verificar'
      preLoaderRoute: typeof VerificarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/times': {
      id: '/times'
      path: '/times'
      fullPath: '/times'
      preLoaderRoute: typeof TimesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultados': {
      id: '/resultados'
      path: '/resultados'
      fullPath: '/resultados'
      preLoaderRoute: typeof ResultadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locais': {
      id: '/locais'
      path: '/locais'
      fullPath: '/locais'
      preLoaderRoute: typeof LocaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atletas': {
      id: '/atletas'
      path: '/atletas'
      fullPath: '/atletas'
      preLoaderRoute: typeof AtletasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/times/$slug': {
      id: '/times/$slug'
      path: '/$slug'
      fullPath: '/times/$slug'
      preLoaderRoute: typeof TimesSlugRouteImport
      parentRoute: typeof TimesRoute
    }
    '/sumula/$partidaId': {
      id: '/sumula/$partidaId'
      path: '/sumula/$partidaId'
      fullPath: '/sumula/$partidaId'
      preLoaderRoute: typeof SumulaPartidaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partidas/$id': {
      id: '/partidas/$id'
      path: '/partidas/$id'
      fullPath: '/partidas/$id'
      preLoaderRoute: typeof PartidasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/torcedor': {
      id: '/onboarding/torcedor'
      path: '/torcedor'
      fullPath: '/onboarding/torcedor'
      preLoaderRoute: typeof OnboardingTorcedorRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/jogador': {
      id: '/onboarding/jogador'
      path: '/jogador'
      fullPath: '/onboarding/jogador'
      preLoaderRoute: typeof OnboardingJogadorRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/diretor': {
      id: '/onboarding/diretor'
      path: '/diretor'
      fullPath: '/onboarding/diretor'
      preLoaderRoute: typeof OnboardingDiretorRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/manifesto/$slug': {
      id: '/manifesto/$slug'
      path: '/manifesto/$slug'
      fullPath: '/manifesto/$slug'
      preLoaderRoute: typeof ManifestoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite/$code': {
      id: '/convite/$code'
      path: '/convite/$code'
      fullPath: '/convite/$code'
      preLoaderRoute: typeof ConviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atletas/$id': {
      id: '/atletas/$id'
      path: '/$id'
      fullPath: '/atletas/$id'
      preLoaderRoute: typeof AtletasIdRouteImport
      parentRoute: typeof AtletasRoute
    }
    '/_authenticated/minha-conta': {
      id: '/_authenticated/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof AuthenticatedMinhaContaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inscricao': {
      id: '/_authenticated/inscricao'
      path: '/inscricao'
      fullPath: '/inscricao'
      preLoaderRoute: typeof AuthenticatedInscricaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/minha-conta/excluir-conta': {
      id: '/_authenticated/minha-conta/excluir-conta'
      path: '/excluir-conta'
      fullPath: '/minha-conta/excluir-conta'
      preLoaderRoute: typeof AuthenticatedMinhaContaExcluirContaRouteImport
      parentRoute: typeof AuthenticatedMinhaContaRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/triagem': {
      id: '/_authenticated/admin/triagem'
      path: '/triagem'
      fullPath: '/admin/triagem'
      preLoaderRoute: typeof AuthenticatedAdminTriagemRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/times': {
      id: '/_authenticated/admin/times'
      path: '/times'
      fullPath: '/admin/times'
      preLoaderRoute: typeof AuthenticatedAdminTimesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sumulas': {
      id: '/_authenticated/admin/sumulas'
      path: '/sumulas'
      fullPath: '/admin/sumulas'
      preLoaderRoute: typeof AuthenticatedAdminSumulasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sorteio': {
      id: '/_authenticated/admin/sorteio'
      path: '/sorteio'
      fullPath: '/admin/sorteio'
      preLoaderRoute: typeof AuthenticatedAdminSorteioRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/notificacoes': {
      id: '/_authenticated/admin/notificacoes'
      path: '/notificacoes'
      fullPath: '/admin/notificacoes'
      preLoaderRoute: typeof AuthenticatedAdminNotificacoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/master-switch': {
      id: '/_authenticated/admin/master-switch'
      path: '/master-switch'
      fullPath: '/admin/master-switch'
      preLoaderRoute: typeof AuthenticatedAdminMasterSwitchRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ligas': {
      id: '/_authenticated/admin/ligas'
      path: '/ligas'
      fullPath: '/admin/ligas'
      preLoaderRoute: typeof AuthenticatedAdminLigasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/financeiro': {
      id: '/_authenticated/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AuthenticatedAdminFinanceiroRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/hooks/wo-checker': {
      id: '/api/public/hooks/wo-checker'
      path: '/api/public/hooks/wo-checker'
      fullPath: '/api/public/hooks/wo-checker'
      preLoaderRoute: typeof ApiPublicHooksWoCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminFinanceiroRoute: typeof AuthenticatedAdminFinanceiroRoute
  AuthenticatedAdminLigasRoute: typeof AuthenticatedAdminLigasRoute
  AuthenticatedAdminMasterSwitchRoute: typeof AuthenticatedAdminMasterSwitchRoute
  AuthenticatedAdminNotificacoesRoute: typeof AuthenticatedAdminNotificacoesRoute
  AuthenticatedAdminSorteioRoute: typeof AuthenticatedAdminSorteioRoute
  AuthenticatedAdminSumulasRoute: typeof AuthenticatedAdminSumulasRoute
  AuthenticatedAdminTimesRoute: typeof AuthenticatedAdminTimesRoute
  AuthenticatedAdminTriagemRoute: typeof AuthenticatedAdminTriagemRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminFinanceiroRoute: AuthenticatedAdminFinanceiroRoute,
  AuthenticatedAdminLigasRoute: AuthenticatedAdminLigasRoute,
  AuthenticatedAdminMasterSwitchRoute: AuthenticatedAdminMasterSwitchRoute,
  AuthenticatedAdminNotificacoesRoute: AuthenticatedAdminNotificacoesRoute,
  AuthenticatedAdminSorteioRoute: AuthenticatedAdminSorteioRoute,
  AuthenticatedAdminSumulasRoute: AuthenticatedAdminSumulasRoute,
  AuthenticatedAdminTimesRoute: AuthenticatedAdminTimesRoute,
  AuthenticatedAdminTriagemRoute: AuthenticatedAdminTriagemRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedMinhaContaRouteChildren {
  AuthenticatedMinhaContaExcluirContaRoute: typeof AuthenticatedMinhaContaExcluirContaRoute
}

const AuthenticatedMinhaContaRouteChildren: AuthenticatedMinhaContaRouteChildren =
  {
    AuthenticatedMinhaContaExcluirContaRoute:
      AuthenticatedMinhaContaExcluirContaRoute,
  }

const AuthenticatedMinhaContaRouteWithChildren =
  AuthenticatedMinhaContaRoute._addFileChildren(
    AuthenticatedMinhaContaRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedInscricaoRoute: typeof AuthenticatedInscricaoRoute
  AuthenticatedMinhaContaRoute: typeof AuthenticatedMinhaContaRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedInscricaoRoute: AuthenticatedInscricaoRoute,
  AuthenticatedMinhaContaRoute: AuthenticatedMinhaContaRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AtletasRouteChildren {
  AtletasIdRoute: typeof AtletasIdRoute
}

const AtletasRouteChildren: AtletasRouteChildren = {
  AtletasIdRoute: AtletasIdRoute,
}

const AtletasRouteWithChildren =
  AtletasRoute._addFileChildren(AtletasRouteChildren)

interface OnboardingRouteChildren {
  OnboardingDiretorRoute: typeof OnboardingDiretorRoute
  OnboardingJogadorRoute: typeof OnboardingJogadorRoute
  OnboardingTorcedorRoute: typeof OnboardingTorcedorRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingDiretorRoute: OnboardingDiretorRoute,
  OnboardingJogadorRoute: OnboardingJogadorRoute,
  OnboardingTorcedorRoute: OnboardingTorcedorRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

interface TimesRouteChildren {
  TimesSlugRoute: typeof TimesSlugRoute
}

const TimesRouteChildren: TimesRouteChildren = {
  TimesSlugRoute: TimesSlugRoute,
}

const TimesRouteWithChildren = TimesRoute._addFileChildren(TimesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AgendaRoute: AgendaRoute,
  AtletasRoute: AtletasRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LocaisRoute: LocaisRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  PrivacidadeRoute: PrivacidadeRoute,
  RankingRoute: RankingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResultadosRoute: ResultadosRoute,
  SignupRoute: SignupRoute,
  TermosRoute: TermosRoute,
  TimesRoute: TimesRouteWithChildren,
  VerificarRoute: VerificarRoute,
  ConviteCodeRoute: ConviteCodeRoute,
  ManifestoSlugRoute: ManifestoSlugRoute,
  PartidasIdRoute: PartidasIdRoute,
  SumulaPartidaIdRoute: SumulaPartidaIdRoute,
  ApiPublicHooksWoCheckerRoute: ApiPublicHooksWoCheckerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
