/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AtletasRouteImport } from './routes/atletas'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedMinhaContaRouteImport } from './routes/_authenticated/minha-conta'
import { Route as AuthenticatedInscricaoRouteImport } from './routes/_authenticated/inscricao'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminTriagemRouteImport } from './routes/_authenticated/admin/triagem'
import { Route as AuthenticatedAdminSorteioRouteImport } from './routes/_authenticated/admin/sorteio'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AtletasRoute = AtletasRouteImport.update({
  id: '/atletas',
  path: '/atletas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMinhaContaRoute = AuthenticatedMinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInscricaoRoute = AuthenticatedInscricaoRouteImport.update({
  id: '/inscricao',
  path: '/inscricao',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminTriagemRoute =
  AuthenticatedAdminTriagemRouteImport.update({
    id: '/triagem',
    path: '/triagem',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSorteioRoute =
  AuthenticatedAdminSorteioRouteImport.update({
    id: '/sorteio',
    path: '/sorteio',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atletas': typeof AtletasRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/inscricao': typeof AuthenticatedInscricaoRoute
  '/minha-conta': typeof AuthenticatedMinhaContaRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/sorteio': typeof AuthenticatedAdminSorteioRoute
  '/admin/triagem': typeof AuthenticatedAdminTriagemRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atletas': typeof AtletasRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/inscricao': typeof AuthenticatedInscricaoRoute
  '/minha-conta': typeof AuthenticatedMinhaContaRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/sorteio': typeof AuthenticatedAdminSorteioRoute
  '/admin/triagem': typeof AuthenticatedAdminTriagemRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/atletas': typeof AtletasRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/inscricao': typeof AuthenticatedInscricaoRoute
  '/_authenticated/minha-conta': typeof AuthenticatedMinhaContaRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/sorteio': typeof AuthenticatedAdminSorteioRoute
  '/_authenticated/admin/triagem': typeof AuthenticatedAdminTriagemRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atletas'
    | '/login'
    | '/signup'
    | '/admin'
    | '/inscricao'
    | '/minha-conta'
    | '/admin/dashboard'
    | '/admin/sorteio'
    | '/admin/triagem'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atletas'
    | '/login'
    | '/signup'
    | '/admin'
    | '/inscricao'
    | '/minha-conta'
    | '/admin/dashboard'
    | '/admin/sorteio'
    | '/admin/triagem'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/atletas'
    | '/login'
    | '/signup'
    | '/_authenticated/admin'
    | '/_authenticated/inscricao'
    | '/_authenticated/minha-conta'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/sorteio'
    | '/_authenticated/admin/triagem'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AtletasRoute: typeof AtletasRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atletas': {
      id: '/atletas'
      path: '/atletas'
      fullPath: '/atletas'
      preLoaderRoute: typeof AtletasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/minha-conta': {
      id: '/_authenticated/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof AuthenticatedMinhaContaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inscricao': {
      id: '/_authenticated/inscricao'
      path: '/inscricao'
      fullPath: '/inscricao'
      preLoaderRoute: typeof AuthenticatedInscricaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/triagem': {
      id: '/_authenticated/admin/triagem'
      path: '/triagem'
      fullPath: '/admin/triagem'
      preLoaderRoute: typeof AuthenticatedAdminTriagemRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sorteio': {
      id: '/_authenticated/admin/sorteio'
      path: '/sorteio'
      fullPath: '/admin/sorteio'
      preLoaderRoute: typeof AuthenticatedAdminSorteioRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminSorteioRoute: typeof AuthenticatedAdminSorteioRoute
  AuthenticatedAdminTriagemRoute: typeof AuthenticatedAdminTriagemRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminSorteioRoute: AuthenticatedAdminSorteioRoute,
  AuthenticatedAdminTriagemRoute: AuthenticatedAdminTriagemRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedInscricaoRoute: typeof AuthenticatedInscricaoRoute
  AuthenticatedMinhaContaRoute: typeof AuthenticatedMinhaContaRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedInscricaoRoute: AuthenticatedInscricaoRoute,
  AuthenticatedMinhaContaRoute: AuthenticatedMinhaContaRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AtletasRoute: AtletasRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
