-- Migration 9: seed admin role
-- Removed hardcoded user_id INSERT to avoid FK violation.
-- Admin role must be inserted manually after the first user registers.
-- Use the seed migration (20260609000000_seed_admin_role.sql) instead.
